version: 2.1
executors:
  docker-executor:
    docker:
      - image: mcr.microsoft.com/playwright:v1.43.0-jammy

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "9b:03:91:c2:5a:d9:6e:55:2a:5a:5c:39:49:8b:43:97"
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Allure Commandline
          command: npm install -g allure-commandline
      - run:
          name: Install Java # Installs Java Development Kit, which is needed to run Java applications.
          command: |
            apt-get update  # Updates the list of available packages and their versions.
            apt-get install -y openjdk-11-jdk
      - run:
          name: Set JAVA_HOME # Sets an environment variable JAVA_HOME that specifies the location of Java.
          command: echo 'export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"' >> $BASH_ENV
      - run:
          name: Update PATH # Updates the system PATH so the shell can find the Java binaries.
          command: echo 'export PATH="$JAVA_HOME/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Install AWS CLI
          command: |
            export DEBIAN_FRONTEND=noninteractive  # Prevents the command line from asking for input.
            ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime  # Sets the server's timezone.
            apt-get update  # Refreshes the repository index.
            apt-get install -y awscli tzdata  # Installs the AWS command line interface and timezone data.
            dpkg-reconfigure --frontend noninteractive tzdata  # Reconfigures installed packages.
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID  
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY  
            aws configure set default.region eu-central-1
      - run:
          name: Define Timestamp # Creates a timestamp for when the job runs, useful for naming files or directories uniquely.
          command: echo 'export TIMESTAMP=$(date +%Y%m%d%H%M%S)' >> $BASH_ENV
      - run:
          name: Create Allure Results Directory
          command: mkdir -p allure-results # Creates a directory to store Allure test results.
      - run:
          name: Download Allure History from S3 # Copies the Allure test history from an S3 bucket to the local machine.
          command: |
            aws s3 cp s3://{{your-bucket-name}}/allure-reports/latest/history ./allure-results/history --recursive
      - run:
          name: Run Playwright Tests
          command: npm test
      - run:
          name: Generate Allure Report with History # Generates a visual report, with the clean option removing old data first.
          command: |
            allure generate allure-results --clean
      - run:
          name: Upload New Allure Report to S3 with Timestamp # Creates a unique directory name for this build's report. / # Syncs the new report to your S3 bucket, making it publicly accessible.
          command: |
            UNIQUE_REPORT_DIR="build-$(echo $CIRCLE_BUILD_NUM)-${TIMESTAMP}"  
            aws s3 sync ./allure-report s3://{{your-bucket-name}}/allure-reports/$UNIQUE_REPORT_DIR --acl public-read
      - run:
          name: Update Latest Report Reference with History # Deletes the current 'latest' directory in your S3 bucket. / # Copies the new report and history data to the 'latest' directory. /
          command: |
            aws s3 rm s3://{{your-bucket-name}}/allure-reports/latest --recursive  
            aws s3 cp --recursive ./allure-report s3://{{your-bucket-name}}/allure-reports/latest/  
            aws s3 cp --recursive ./allure-report/history s3://{{your-bucket-name}}/allure-reports/latest/history/
      - run:
          name: Display Allure Report URL with Timestamp # Prints the URL where the report can be accessed.
          command: echo "Allure report is available at https://{{your-bucket-name}}.s3.eu-central-1.amazonaws.com/allure-reports/${UNIQUE_REPORT_DIR}/index.html" > allure-report-url.txt
      - store_artifacts:
          path: allure-report-url.txt
          destination: allure-report-url

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
